### ISSUE TITLE
	ipt "github.com/coreos/go-iptables/iptables" not found

### ISSUE THREAD

**Issue by mishar** [kilo-io/iptables_parser#9]
I want to parse a full iptables-save using your go lib. I see the example and figure I will need the go-iptables modules. but that's not available. Essentially,  I wanted to use your lib to run it over a dumped iptable which has bunch of chain and rules. I see that parser.go can do it. But I am unsure what to do to load the table dump. Any pointer will be appreciated

**Comment by leonnicolas** [comment]
Sorry for the long response time. Could you resolve the issue? I am not sure if I understand your problem. In the example code, we use CoreOS' iptables package to get the dump.
